/**
 * Tools Registry - 100+ functional tools organized by category
 */

import { Tool, ToolCategoryInfo } from "@/lib/types/tools";

// JSON Tools (15 tools)
const jsonTools: Tool[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    category: "json",
    description: "What is a JSON formatter? This free online tool formats and beautifies JSON data with proper indentation and syntax highlighting, making it easy to read and understand. Perfect for developers working with APIs, configuration files, or debugging JSON responses. Use it to transform messy, minified JSON into clean, readable code instantly in your browser.",
    route: "/tools/json/formatter",
    icon: "FileJson",
    tags: ["formatter", "beautifier", "json", "pretty-print"],
    keywords: ["json formatter", "json beautifier", "format json", "pretty print json"],
    isClientSide: true,
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    category: "json",
    description: "Validate JSON syntax and check for errors instantly with this free online JSON validator. This tool helps developers identify syntax errors, missing commas, unclosed brackets, and other common JSON issues before they cause problems in production. Essential for debugging API responses, configuration files, and data validation workflows.",
    route: "/tools/json/validator",
    icon: "CheckCircle",
    tags: ["validator", "json", "syntax-check"],
    keywords: ["json validator", "validate json", "json syntax checker"],
    isClientSide: true,
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    category: "json",
    description: "Minify JSON by removing whitespace and unnecessary characters to reduce file size and improve performance. This free tool is perfect for production environments where smaller file sizes matter for faster API responses and reduced bandwidth usage. Ideal for web developers optimizing JSON payloads for mobile apps and web services.",
    route: "/tools/json/minifier",
    icon: "Minimize2",
    tags: ["minifier", "json", "compress"],
    keywords: ["json minifier", "minify json", "compress json"],
    isClientSide: true,
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    category: "json",
    description: "Convert JSON data to CSV format quickly and easily with this free online converter. Perfect for exporting JSON API responses to Excel, Google Sheets, or other spreadsheet applications. This tool automatically handles nested JSON structures and arrays, making it ideal for data analysts, developers, and anyone working with structured data.",
    route: "/tools/json/to-csv",
    icon: "FileSpreadsheet",
    tags: ["converter", "json", "csv", "export"],
    keywords: ["json to csv", "convert json csv", "json csv converter"],
    isClientSide: true,
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    category: "json",
    description: "Convert JSON data to XML format instantly with this free online converter. Essential for developers working with legacy systems, SOAP APIs, or enterprise applications that require XML format. This tool handles complex nested structures and automatically generates proper XML tags, making data transformation seamless.",
    route: "/tools/json/to-xml",
    icon: "FileCode",
    tags: ["converter", "json", "xml"],
    keywords: ["json to xml", "convert json xml", "json xml converter"],
    isClientSide: true,
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    category: "json",
    description: "Convert JSON data to YAML format with this free online converter. Perfect for DevOps engineers, developers working with configuration files, Docker Compose, Kubernetes manifests, or CI/CD pipelines. YAML's human-readable format makes configuration management easier, and this tool ensures accurate conversion every time.",
    route: "/tools/json/to-yaml",
    icon: "FileText",
    tags: ["converter", "json", "yaml"],
    keywords: ["json to yaml", "convert json yaml", "json yaml converter"],
    isClientSide: true,
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    category: "json",
    description: "Compare two JSON objects and highlight differences side-by-side with this free online JSON diff tool. Essential for developers tracking API changes, debugging configuration updates, or reviewing code changes. This tool makes it easy to spot additions, deletions, and modifications in complex JSON structures.",
    route: "/tools/json/diff",
    icon: "GitCompare",
    tags: ["diff", "compare", "json"],
    keywords: ["json diff", "compare json", "json difference"],
    isClientSide: true,
  },
  {
    id: "json-path-finder",
    name: "JSON Path Finder",
    category: "json",
    description: "Find and extract values from JSON data using JSONPath expressions with this powerful free tool. Similar to XPath for XML, JSONPath allows you to query and navigate complex JSON structures easily. Perfect for developers extracting specific data from large JSON responses, API testing, or data transformation tasks.",
    route: "/tools/json/path-finder",
    icon: "Search",
    tags: ["jsonpath", "extract", "query"],
    keywords: ["json path", "jsonpath", "json query"],
    isClientSide: true,
  },
  {
    id: "json-schema-validator",
    name: "JSON Schema Validator",
    category: "json",
    description: "Validate JSON data against a JSON Schema to ensure it meets your structure and validation rules. This free tool is essential for API developers, data engineers, and anyone working with structured data validation. Ensure your JSON conforms to expected formats, data types, and constraints before processing.",
    route: "/tools/json/schema-validator",
    icon: "ShieldCheck",
    tags: ["schema", "validator", "json"],
    keywords: ["json schema", "schema validator", "validate schema"],
    isClientSide: true,
  },
  {
    id: "json-merge",
    name: "JSON Merger",
    category: "json",
    description: "Merge multiple JSON objects into one unified structure with this free online tool. Perfect for combining configuration files, merging API responses, or consolidating data from multiple sources. This tool handles key conflicts intelligently and preserves nested structures, making data integration seamless.",
    route: "/tools/json/merge",
    icon: "Merge",
    tags: ["merge", "combine", "json"],
    keywords: ["json merge", "merge json", "combine json"],
    isClientSide: true,
  },
  {
    id: "json-escape",
    name: "JSON Escape/Unescape",
    category: "json",
    description: "Escape or unescape special characters in JSON strings to ensure proper encoding and prevent parsing errors. This free tool is essential when embedding JSON in HTML, JavaScript, or other contexts where special characters need escaping. Also useful for decoding escaped JSON strings back to their original format.",
    route: "/tools/json/escape",
    icon: "Lock",
    tags: ["escape", "unescape", "json"],
    keywords: ["json escape", "escape json", "json unescape"],
    isClientSide: true,
  },
  {
    id: "json-key-sorter",
    name: "JSON Key Sorter",
    category: "json",
    description: "Sort JSON object keys alphabetically to organize and standardize your JSON data structure. This free tool helps maintain consistency across configuration files, makes comparisons easier, and improves code readability. Perfect for developers working with large JSON files or maintaining consistent data formats.",
    route: "/tools/json/key-sorter",
    icon: "ArrowUpDown",
    tags: ["sort", "keys", "json"],
    keywords: ["json sort", "sort json keys", "json key sorter"],
    isClientSide: true,
  },
  {
    id: "json-to-typescript",
    name: "JSON to TypeScript",
    category: "json",
    description: "Generate TypeScript interfaces and type definitions from JSON data automatically with this free online tool. Save hours of manual typing when working with TypeScript projects, React components, or Node.js applications. This tool analyzes your JSON structure and creates accurate, type-safe interfaces that match your data exactly.",
    route: "/tools/json/to-typescript",
    icon: "Code",
    tags: ["typescript", "generator", "json"],
    keywords: ["json to typescript", "json typescript", "generate typescript"],
    isClientSide: true,
  },
  {
    id: "json-to-sql",
    name: "JSON to SQL",
    category: "json",
    description: "Convert JSON data to SQL INSERT statements quickly and accurately with this free online converter. Perfect for database administrators, developers migrating data, or anyone needing to import JSON data into SQL databases. This tool generates properly formatted INSERT statements that are ready to execute in your database.",
    route: "/tools/json/to-sql",
    icon: "Database",
    tags: ["sql", "converter", "json"],
    keywords: ["json to sql", "json sql", "convert json sql"],
    isClientSide: true,
  },
  {
    id: "json-tree-viewer",
    name: "JSON Tree Viewer",
    category: "json",
    description: "Visualize JSON data in an interactive tree structure that makes complex nested data easy to navigate and understand. This free tool is perfect for exploring large JSON files, debugging API responses, or teaching JSON structure. The visual tree format helps you quickly locate specific values and understand data relationships.",
    route: "/tools/json/tree-viewer",
    icon: "TreePine",
    tags: ["tree", "viewer", "visualize", "json"],
    keywords: ["json tree", "json viewer", "json tree viewer"],
    isClientSide: true,
  },
];

// Text Tools (24 tools)
const textTools: Tool[] = [
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    category: "text",
    description: "Convert text between different cases instantly: uppercase, lowercase, title case, sentence case, camelCase, kebab-case, snake_case, and PascalCase. This free online tool is perfect for developers, content creators, and anyone working with code or text formatting. Transform your text with a single click - no coding required!",
    route: "/tools/text/case-converter",
    icon: "Type",
    tags: ["case", "converter", "text", "transform"],
    keywords: ["text case converter", "case converter", "text transform"],
    isClientSide: true,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    category: "text",
    description: "Count words, characters, sentences, and paragraphs in text",
    route: "/tools/text/word-counter",
    icon: "FileText",
    tags: ["counter", "words", "characters", "text"],
    keywords: ["word counter", "character counter", "text counter"],
    isClientSide: true,
  },
  {
    id: "character-counter",
    name: "Character Counter",
    category: "text",
    description: "Count characters, words, and lines in text",
    route: "/tools/text/character-counter",
    icon: "Hash",
    tags: ["counter", "characters", "text"],
    keywords: ["character counter", "char count", "text counter"],
    isClientSide: true,
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    category: "text",
    description: "Reverse text character by character or word by word",
    route: "/tools/text/reverser",
    icon: "ArrowLeftRight",
    tags: ["reverse", "text", "transform"],
    keywords: ["reverse text", "text reverser", "flip text"],
    isClientSide: true,
  },
  {
    id: "text-duplicate-remover",
    name: "Remove Duplicates",
    category: "text",
    description: "Remove duplicate lines or words from text",
    route: "/tools/text/duplicate-remover",
    icon: "X",
    tags: ["duplicate", "remove", "text", "clean"],
    keywords: ["remove duplicates", "duplicate remover", "text cleaner"],
    isClientSide: true,
  },
  {
    id: "text-sort-lines",
    name: "Sort Text Lines",
    category: "text",
    description: "Sort lines of text alphabetically or numerically",
    route: "/tools/text/sort-lines",
    icon: "ArrowUpDown",
    tags: ["sort", "lines", "text"],
    keywords: ["sort lines", "text sorter", "sort text"],
    isClientSide: true,
  },
  {
    id: "text-replace",
    name: "Find and Replace",
    category: "text",
    description: "Find and replace text with support for regex",
    route: "/tools/text/replace",
    icon: "Replace",
    tags: ["replace", "find", "text", "regex"],
    keywords: ["find replace", "text replace", "search replace"],
    isClientSide: true,
  },
  {
    id: "text-extract-urls",
    name: "Extract URLs",
    category: "text",
    description: "Extract all URLs from text",
    route: "/tools/text/extract-urls",
    icon: "Link",
    tags: ["extract", "urls", "links", "text"],
    keywords: ["extract urls", "url extractor", "find urls"],
    isClientSide: true,
  },
  {
    id: "text-extract-emails",
    name: "Extract Emails",
    category: "text",
    description: "Extract all email addresses from text",
    route: "/tools/text/extract-emails",
    icon: "Mail",
    tags: ["extract", "emails", "text"],
    keywords: ["extract emails", "email extractor", "find emails"],
    isClientSide: true,
  },
  {
    id: "text-extract-numbers",
    name: "Extract Numbers",
    category: "text",
    description: "Extract all numbers from text",
    route: "/tools/text/extract-numbers",
    icon: "Hash",
    tags: ["extract", "numbers", "text"],
    keywords: ["extract numbers", "number extractor", "find numbers"],
    isClientSide: true,
  },
  {
    id: "text-add-line-numbers",
    name: "Add Line Numbers",
    category: "text",
    description: "Add line numbers to each line of text",
    route: "/tools/text/add-line-numbers",
    icon: "List",
    tags: ["line numbers", "text", "format"],
    keywords: ["add line numbers", "line numbers", "number lines"],
    isClientSide: true,
  },
  {
    id: "text-remove-line-numbers",
    name: "Remove Line Numbers",
    category: "text",
    description: "Remove line numbers from text",
    route: "/tools/text/remove-line-numbers",
    icon: "ListX",
    tags: ["line numbers", "remove", "text"],
    keywords: ["remove line numbers", "strip line numbers"],
    isClientSide: true,
  },
  {
    id: "text-to-base64",
    name: "Text to Base64",
    category: "text",
    description: "Encode text to Base64 format",
    route: "/tools/text/to-base64",
    icon: "Lock",
    tags: ["base64", "encode", "text"],
    keywords: ["text to base64", "base64 encode", "encode base64"],
    isClientSide: true,
  },
  {
    id: "base64-to-text",
    name: "Base64 to Text",
    category: "text",
    description: "Decode Base64 to text",
    route: "/tools/text/from-base64",
    icon: "Unlock",
    tags: ["base64", "decode", "text"],
    keywords: ["base64 to text", "base64 decode", "decode base64"],
    isClientSide: true,
  },
  {
    id: "text-to-binary",
    name: "Text to Binary",
    category: "text",
    description: "Convert text to binary representation",
    route: "/tools/text/to-binary",
    icon: "Binary",
    tags: ["binary", "convert", "text"],
    keywords: ["text to binary", "binary converter", "text binary"],
    isClientSide: true,
  },
  {
    id: "binary-to-text",
    name: "Binary to Text",
    category: "text",
    description: "Convert binary to text",
    route: "/tools/text/from-binary",
    icon: "FileText",
    tags: ["binary", "convert", "text"],
    keywords: ["binary to text", "binary decoder", "decode binary"],
    isClientSide: true,
  },
  {
    id: "text-to-hex",
    name: "Text to Hex",
    category: "text",
    description: "Convert text to hexadecimal representation",
    route: "/tools/text/to-hex",
    icon: "Hash",
    tags: ["hex", "convert", "text"],
    keywords: ["text to hex", "hex converter", "text hex"],
    isClientSide: true,
  },
  {
    id: "hex-to-text",
    name: "Hex to Text",
    category: "text",
    description: "Convert hexadecimal to text",
    route: "/tools/text/from-hex",
    icon: "FileText",
    tags: ["hex", "convert", "text"],
    keywords: ["hex to text", "hex decoder", "decode hex"],
    isClientSide: true,
  },
  {
    id: "text-to-morse",
    name: "Text to Morse Code",
    category: "text",
    description: "Convert text to Morse code",
    route: "/tools/text/to-morse",
    icon: "Radio",
    tags: ["morse", "convert", "text"],
    keywords: ["text to morse", "morse code", "morse converter"],
    isClientSide: true,
  },
  {
    id: "morse-to-text",
    name: "Morse Code to Text",
    category: "text",
    description: "Convert Morse code to text",
    route: "/tools/text/from-morse",
    icon: "Radio",
    tags: ["morse", "convert", "text"],
    keywords: ["morse to text", "morse decoder", "decode morse"],
    isClientSide: true,
  },
  {
    id: "text-hash-generator",
    name: "Text Hash Generator",
    category: "text",
    description: "Generate cryptographic hashes (MD5, SHA1, SHA256, SHA512) from any text instantly with this free online hash generator. Essential for developers working with password hashing, data integrity verification, digital signatures, or security applications. All hashing happens client-side in your browser for maximum security and privacy.",
    route: "/tools/text/hash-generator",
    icon: "Fingerprint",
    tags: ["hash", "md5", "sha", "crypto"],
    keywords: ["hash generator", "md5", "sha256", "text hash"],
    isClientSide: true,
  },
  {
    id: "text-slug-generator",
    name: "Slug Generator",
    category: "text",
    description: "Generate URL-friendly slugs from text",
    route: "/tools/text/slug-generator",
    icon: "Link",
    tags: ["slug", "url", "seo", "text"],
    keywords: ["slug generator", "url slug", "text slug"],
    isClientSide: true,
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    category: "text",
    description: "Generate Lorem Ipsum placeholder text",
    route: "/tools/text/lorem-ipsum",
    icon: "FileText",
    tags: ["lorem", "placeholder", "text", "generator"],
    keywords: ["lorem ipsum", "placeholder text", "dummy text"],
    isClientSide: true,
  },
];

// Image Tools (17 tools)
const imageTools: Tool[] = [
  {
    id: "image-resizer",
    name: "Image Resizer",
    category: "image",
    description: "Resize images to specific dimensions while maintaining aspect ratio. Perfect for optimizing images for web, social media, or print. All processing happens in your browser.",
    route: "/tools/image/resizer",
    icon: "Maximize2",
    tags: ["resize", "image", "dimensions"],
    keywords: ["image resizer", "resize image", "image size"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-cropper", "image-format-converter", "image-compressor"],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    category: "image",
    description: "Compress images to reduce file size while maintaining quality",
    route: "/tools/image/compressor",
    icon: "Minimize2",
    tags: ["compress", "image", "optimize"],
    keywords: ["image compressor", "compress image", "reduce image size"],
    isClientSide: true,
    isImplemented: true,
  },
  {
    id: "image-format-converter",
    name: "Image Format Converter",
    category: "image",
    description: "Convert images between JPG, PNG, WebP, AVIF formats",
    route: "/tools/image/format-converter",
    icon: "RefreshCw",
    tags: ["convert", "format", "image", "jpg", "png", "webp"],
    keywords: ["image converter", "convert image format", "jpg to png"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-resizer", "image-compressor", "image-to-base64"],
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    category: "image",
    description: "Crop images to specific dimensions or aspect ratios",
    route: "/tools/image/cropper",
    icon: "Crop",
    tags: ["crop", "image", "edit"],
    keywords: ["image cropper", "crop image", "image crop tool"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-resizer", "image-rotator", "image-format-converter"],
  },
  {
    id: "image-rotator",
    name: "Image Rotator",
    category: "image",
    description: "Rotate images by 90, 180, or 270 degrees",
    route: "/tools/image/rotator",
    icon: "RotateCw",
    tags: ["rotate", "image", "edit"],
    keywords: ["image rotator", "rotate image", "image rotation"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-cropper", "image-format-converter", "image-blur"],
  },
  {
    id: "image-watermark",
    name: "Image Watermark",
    category: "image",
    description: "Add text or image watermarks to images with customizable position, opacity, and styling. Protect your images and add branding with professional watermarking.",
    route: "/tools/image/watermark",
    icon: "Droplet",
    tags: ["watermark", "image", "edit"],
    keywords: ["image watermark", "add watermark", "watermark tool"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-filters", "image-collage", "image-cropper"],
  },
  {
    id: "image-filters",
    name: "Image Filters",
    category: "image",
    description: "Apply professional filters and effects to your images. Choose from grayscale, sepia, invert, vintage, black & white, and sharpen filters with adjustable intensity controls.",
    route: "/tools/image/filters",
    icon: "Palette",
    tags: ["filters", "effects", "image", "edit"],
    keywords: ["image filters", "photo filters", "image effects"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-blur", "image-brightness-contrast", "image-watermark"],
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    category: "image",
    description: "Convert images to Base64 data URLs instantly. Perfect for embedding images in HTML, CSS, or data URIs. Supports PNG, JPG, GIF, WebP, and more.",
    route: "/tools/image/to-base64",
    icon: "Lock",
    tags: ["base64", "encode", "image"],
    keywords: ["image to base64", "base64 image", "encode image"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["base64-to-image", "base64-encoder", "image-format-converter"],
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image",
    category: "image",
    description: "Convert Base64 data URLs to images. Decode Base64 strings and download as image files. Perfect for extracting images from Base64 encoded data.",
    route: "/tools/image/from-base64",
    icon: "Unlock",
    tags: ["base64", "decode", "image"],
    keywords: ["base64 to image", "decode base64 image"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-to-base64", "base64-encoder", "image-format-converter"],
  },
  {
    id: "image-metadata",
    name: "Image Metadata Extractor",
    category: "image",
    description: "Extract EXIF and other metadata from images. View camera settings, GPS location, creation date, and more. Perfect for photographers and content creators.",
    route: "/tools/image/metadata",
    icon: "Info",
    tags: ["metadata", "exif", "image"],
    keywords: ["image metadata", "exif data", "image info"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-color-picker", "image-to-base64", "image-format-converter"],
  },
  {
    id: "image-color-picker",
    name: "Image Color Picker",
    category: "image",
    description: "Pick colors from images and generate color palettes. Click anywhere on an image to get the exact color value in HEX, RGB, and HSL formats. Perfect for designers and developers.",
    route: "/tools/image/color-picker",
    icon: "Droplet",
    tags: ["color", "picker", "palette", "image"],
    keywords: ["color picker", "image color", "color palette"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["color-picker", "color-palette-generator", "image-metadata"],
  },
  {
    id: "image-background-remover",
    name: "Background Remover",
    category: "image",
    description: "Remove backgrounds from images using AI",
    route: "/tools/image/background-remover",
    icon: "Scissors",
    tags: ["background", "remove", "ai", "image"],
    keywords: ["remove background", "background remover", "transparent background"],
    isClientSide: true,
    isImplemented: true,
  },
  {
    id: "image-blur",
    name: "Image Blur Tool",
    category: "image",
    description: "Apply blur effects to images with adjustable intensity. Perfect for creating privacy effects, background blur, or artistic effects. All processing happens in your browser.",
    route: "/tools/image/blur",
    icon: "Blur",
    tags: ["blur", "image", "edit"],
    keywords: ["image blur", "blur tool", "blur image"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-brightness-contrast", "image-filters", "image-rotator"],
  },
  {
    id: "image-brightness-contrast",
    name: "Brightness & Contrast",
    category: "image",
    description: "Adjust brightness and contrast of images with precise controls. Perfect for photo editing, correcting exposure, and enhancing image quality. All processing happens in your browser.",
    route: "/tools/image/brightness-contrast",
    icon: "Sun",
    tags: ["brightness", "contrast", "image", "edit"],
    keywords: ["image brightness", "image contrast", "adjust image"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-blur", "image-filters", "image-rotator"],
  },
  {
    id: "image-collage",
    name: "Image Collage Maker",
    category: "image",
    description: "Create beautiful collages from multiple images. Choose from grid, horizontal, or vertical layouts. Customize spacing, background color, and grid dimensions for perfect compositions.",
    route: "/tools/image/collage",
    icon: "LayoutGrid",
    tags: ["collage", "combine", "image"],
    keywords: ["image collage", "collage maker", "combine images"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-watermark", "image-filters", "image-cropper"],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    category: "image",
    description: "Generate QR codes from text, URLs, or any data instantly with this free online QR code generator. Perfect for marketing campaigns, business cards, event tickets, WiFi passwords, or contact information sharing. Customize size, error correction level, and download as PNG or SVG - all without registration or payment.",
    route: "/tools/image/qr-generator",
    icon: "QrCode",
    tags: ["qr code", "generator", "barcode"],
    keywords: ["qr code generator", "generate qr code", "qr code"],
    isClientSide: true,
  },
  {
    id: "qr-code-reader",
    name: "QR Code Reader",
    category: "image",
    description: "Read and decode QR codes from images",
    route: "/tools/image/qr-reader",
    icon: "Scan",
    tags: ["qr code", "reader", "decode", "barcode"],
    keywords: ["qr code reader", "read qr code", "qr decoder"],
    isClientSide: true,
  },
];

// PDF Tools (15 tools)
const pdfTools: Tool[] = [
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    category: "pdf",
    description: "Extract text content from PDF files",
    route: "/tools/pdf/to-text",
    icon: "FileText",
    tags: ["pdf", "text", "extract", "converter"],
    keywords: ["pdf to text", "extract text from pdf", "pdf text converter"],
    isClientSide: false,
    isImplemented: true,
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    category: "pdf",
    description: "Convert PDF pages to images",
    route: "/tools/pdf/to-image",
    icon: "Image",
    tags: ["pdf", "image", "converter"],
    keywords: ["pdf to image", "pdf to jpg", "pdf to png"],
    isClientSide: false,
  },
  {
    id: "pdf-merger",
    name: "PDF Merger",
    category: "pdf",
    description: "Merge multiple PDF files into one",
    route: "/tools/pdf/merger",
    icon: "Merge",
    tags: ["pdf", "merge", "combine"],
    keywords: ["pdf merger", "merge pdf", "combine pdf"],
    isClientSide: false,
    isImplemented: true,
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    category: "pdf",
    description: "Split PDF files into multiple files",
    route: "/tools/pdf/splitter",
    icon: "Scissors",
    tags: ["pdf", "split", "divide"],
    keywords: ["pdf splitter", "split pdf", "divide pdf"],
    isClientSide: false,
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    category: "pdf",
    description: "Compress PDF files to reduce file size",
    route: "/tools/pdf/compressor",
    icon: "Minimize2",
    tags: ["pdf", "compress", "optimize"],
    keywords: ["pdf compressor", "compress pdf", "reduce pdf size"],
    isClientSide: false,
  },
  {
    id: "pdf-rotator",
    name: "PDF Rotator",
    category: "pdf",
    description: "Rotate PDF pages",
    route: "/tools/pdf/rotator",
    icon: "RotateCw",
    tags: ["pdf", "rotate", "edit"],
    keywords: ["pdf rotator", "rotate pdf", "pdf rotation"],
    isClientSide: false,
  },
  {
    id: "pdf-watermark",
    name: "PDF Watermark",
    category: "pdf",
    description: "Add watermarks to PDF files",
    route: "/tools/pdf/watermark",
    icon: "Droplet",
    tags: ["pdf", "watermark", "edit"],
    keywords: ["pdf watermark", "add watermark pdf", "watermark tool"],
    isClientSide: false,
  },
  {
    id: "pdf-page-extractor",
    name: "PDF Page Extractor",
    category: "pdf",
    description: "Extract specific pages from PDF files",
    route: "/tools/pdf/page-extractor",
    icon: "File",
    tags: ["pdf", "extract", "pages"],
    keywords: ["pdf page extractor", "extract pdf pages", "pdf pages"],
    isClientSide: false,
  },
  {
    id: "pdf-page-reorder",
    name: "PDF Page Reorder",
    category: "pdf",
    description: "Reorder pages in PDF files",
    route: "/tools/pdf/page-reorder",
    icon: "ArrowUpDown",
    tags: ["pdf", "reorder", "pages"],
    keywords: ["pdf reorder", "reorder pdf pages", "pdf page order"],
    isClientSide: false,
  },
  {
    id: "pdf-metadata",
    name: "PDF Metadata Editor",
    category: "pdf",
    description: "Edit PDF metadata (title, author, subject, etc.)",
    route: "/tools/pdf/metadata",
    icon: "Edit",
    tags: ["pdf", "metadata", "edit"],
    keywords: ["pdf metadata", "edit pdf metadata", "pdf info"],
    isClientSide: false,
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF",
    category: "pdf",
    description: "Convert text to PDF format",
    route: "/tools/pdf/from-text",
    icon: "FileText",
    tags: ["pdf", "text", "converter"],
    keywords: ["text to pdf", "create pdf", "text pdf converter"],
    isClientSide: false,
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    category: "pdf",
    description: "Convert images to PDF format",
    route: "/tools/pdf/from-image",
    icon: "Image",
    tags: ["pdf", "image", "converter"],
    keywords: ["image to pdf", "jpg to pdf", "png to pdf"],
    isClientSide: false,
  },
  {
    id: "pdf-password-protect",
    name: "PDF Password Protector",
    category: "pdf",
    description: "Add password protection to PDF files",
    route: "/tools/pdf/password-protect",
    icon: "Lock",
    tags: ["pdf", "password", "security"],
    keywords: ["pdf password", "protect pdf", "password protect pdf"],
    isClientSide: false,
  },
  {
    id: "pdf-password-remover",
    name: "PDF Password Remover",
    category: "pdf",
    description: "Remove password protection from PDF files",
    route: "/tools/pdf/password-remover",
    icon: "Unlock",
    tags: ["pdf", "password", "remove"],
    keywords: ["remove pdf password", "unlock pdf", "pdf password remover"],
    isClientSide: false,
  },
  {
    id: "pdf-form-filler",
    name: "PDF Form Filler",
    category: "pdf",
    description: "Fill PDF forms programmatically",
    route: "/tools/pdf/form-filler",
    icon: "FileEdit",
    tags: ["pdf", "form", "fill"],
    keywords: ["pdf form filler", "fill pdf form", "pdf form"],
    isClientSide: false,
  },
];

// HTML Tools (15 tools)
const htmlTools: Tool[] = [
  {
    id: "html-formatter",
    name: "HTML Formatter",
    category: "html",
    description: "Format and beautify HTML code",
    route: "/tools/html/formatter",
    icon: "Code",
    tags: ["html", "formatter", "beautifier"],
    keywords: ["html formatter", "format html", "beautify html"],
    isClientSide: true,
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    category: "html",
    description: "Minify HTML by removing whitespace and comments",
    route: "/tools/html/minifier",
    icon: "Minimize2",
    tags: ["html", "minifier", "compress"],
    keywords: ["html minifier", "minify html", "compress html"],
    isClientSide: true,
  },
  {
    id: "html-validator",
    name: "HTML Validator",
    category: "html",
    description: "Validate HTML code for errors and warnings",
    route: "/tools/html/validator",
    icon: "CheckCircle",
    tags: ["html", "validator", "validate"],
    keywords: ["html validator", "validate html", "html checker"],
    isClientSide: true,
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    category: "html",
    description: "Convert HTML to Markdown format",
    route: "/tools/html/to-markdown",
    icon: "FileText",
    tags: ["html", "markdown", "converter"],
    keywords: ["html to markdown", "convert html markdown"],
    isClientSide: true,
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    category: "html",
    description: "Convert Markdown to HTML format",
    route: "/tools/html/from-markdown",
    icon: "Code",
    tags: ["markdown", "html", "converter"],
    keywords: ["markdown to html", "convert markdown html"],
    isClientSide: true,
  },
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder/Decoder",
    category: "html",
    description: "Encode or decode HTML entities",
    route: "/tools/html/entity-encoder",
    icon: "Lock",
    tags: ["html", "entity", "encode", "decode"],
    keywords: ["html entity", "encode html", "decode html"],
    isClientSide: true,
  },
  {
    id: "html-tag-remover",
    name: "HTML Tag Remover",
    category: "html",
    description: "Remove HTML tags from text",
    route: "/tools/html/tag-remover",
    icon: "X",
    tags: ["html", "tags", "remove", "strip"],
    keywords: ["remove html tags", "strip html", "html tag remover"],
    isClientSide: true,
  },
  {
    id: "html-color-picker",
    name: "HTML Color Picker",
    category: "html",
    description: "Pick colors and generate HTML color codes",
    route: "/tools/html/color-picker",
    icon: "Droplet",
    tags: ["html", "color", "picker"],
    keywords: ["html color picker", "color picker", "html color"],
    isClientSide: true,
  },
  {
    id: "html-table-generator",
    name: "HTML Table Generator",
    category: "html",
    description: "Generate HTML table code from data",
    route: "/tools/html/table-generator",
    icon: "Table",
    tags: ["html", "table", "generator"],
    keywords: ["html table generator", "table generator", "html table"],
    isClientSide: true,
  },
  {
    id: "html-to-jsx",
    name: "HTML to JSX",
    category: "html",
    description: "Convert HTML to JSX format",
    route: "/tools/html/to-jsx",
    icon: "Code",
    tags: ["html", "jsx", "react", "converter"],
    keywords: ["html to jsx", "convert html jsx", "html jsx converter"],
    isClientSide: true,
  },
  {
    id: "html-css-inliner",
    name: "HTML CSS Inliner",
    category: "html",
    description: "Inline CSS styles into HTML elements",
    route: "/tools/html/css-inliner",
    icon: "Palette",
    tags: ["html", "css", "inline"],
    keywords: ["html css inliner", "inline css", "css inline"],
    isClientSide: true,
  },
  {
    id: "html-link-extractor",
    name: "HTML Link Extractor",
    category: "html",
    description: "Extract all links from HTML",
    route: "/tools/html/link-extractor",
    icon: "Link",
    tags: ["html", "links", "extract"],
    keywords: ["html link extractor", "extract links", "html links"],
    isClientSide: true,
  },
  {
    id: "html-image-extractor",
    name: "HTML Image Extractor",
    category: "html",
    description: "Extract all image sources from HTML",
    route: "/tools/html/image-extractor",
    icon: "Image",
    tags: ["html", "images", "extract"],
    keywords: ["html image extractor", "extract images", "html images"],
    isClientSide: true,
  },
  {
    id: "html-meta-generator",
    name: "HTML Meta Tag Generator",
    category: "html",
    description: "Generate comprehensive HTML meta tags for SEO optimization. Create meta tags for search engines, Open Graph tags for social media, and Twitter Cards. Perfect for website developers and SEO specialists.",
    route: "/tools/html/meta-generator",
    icon: "Tag",
    tags: ["html", "meta", "seo", "generator"],
    keywords: ["html meta tags", "meta tag generator", "seo meta"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["meta-tag-generator", "open-graph-generator", "twitter-card-generator"],
  },
  {
    id: "html-favicon-generator",
    name: "HTML Favicon Generator",
    category: "html",
    description: "Generate favicon HTML code from images. Create favicons in multiple sizes (16x16, 32x32, 48x48, 180x180) and get ready-to-use HTML code for your website.",
    route: "/tools/html/favicon-generator",
    icon: "Star",
    tags: ["html", "favicon", "generator"],
    keywords: ["favicon generator", "html favicon", "generate favicon"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["image-resizer", "html-meta-generator", "image-format-converter"],
  },
];

// SEO Tools (15 tools)
const seoTools: Tool[] = [
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    category: "seo",
    description: "Generate comprehensive meta tags for SEO optimization including title, description, Open Graph tags, and Twitter Cards. This free tool helps website owners, marketers, and developers create properly formatted meta tags that improve search engine visibility and social media sharing. Includes best practices and character limits for optimal results.",
    route: "/tools/seo/meta-tag-generator",
    icon: "Tag",
    tags: ["seo", "meta", "tags", "generator"],
    keywords: ["meta tag generator", "seo meta tags", "meta tags"],
    isClientSide: true,
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    category: "seo",
    description: "Generate XML sitemaps for websites",
    route: "/tools/seo/sitemap-generator",
    icon: "Map",
    tags: ["seo", "sitemap", "xml", "generator"],
    keywords: ["sitemap generator", "xml sitemap", "generate sitemap"],
    isClientSide: true,
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    category: "seo",
    description: "Generate robots.txt file for search engines",
    route: "/tools/seo/robots-txt-generator",
    icon: "Bot",
    tags: ["seo", "robots", "txt", "generator"],
    keywords: ["robots.txt generator", "robots txt", "generate robots"],
    isClientSide: true,
  },
  {
    id: "schema-markup-generator",
    name: "Schema Markup Generator",
    category: "seo",
    description: "Generate JSON-LD schema markup for structured data",
    route: "/tools/seo/schema-generator",
    icon: "FileJson",
    tags: ["seo", "schema", "json-ld", "structured-data"],
    keywords: ["schema markup", "json-ld generator", "structured data"],
    isClientSide: true,
  },
  {
    id: "open-graph-generator",
    name: "Open Graph Tag Generator",
    category: "seo",
    description: "Generate Open Graph meta tags for social media",
    route: "/tools/seo/open-graph-generator",
    icon: "Share2",
    tags: ["seo", "open graph", "social", "meta"],
    keywords: ["open graph generator", "og tags", "social meta tags"],
    isClientSide: true,
  },
  {
    id: "twitter-card-generator",
    name: "Twitter Card Generator",
    category: "seo",
    description: "Generate Twitter Card meta tags",
    route: "/tools/seo/twitter-card-generator",
    icon: "Twitter",
    tags: ["seo", "twitter", "card", "meta"],
    keywords: ["twitter card generator", "twitter meta", "twitter cards"],
    isClientSide: true,
  },
  {
    id: "url-slug-generator",
    name: "URL Slug Generator",
    category: "seo",
    description: "Generate SEO-friendly URL slugs",
    route: "/tools/seo/url-slug-generator",
    icon: "Link",
    tags: ["seo", "slug", "url", "generator"],
    keywords: ["url slug generator", "slug generator", "seo slug"],
    isClientSide: true,
  },
  {
    id: "keyword-density-checker",
    name: "Keyword Density Checker",
    category: "seo",
    description: "Check keyword density in text content",
    route: "/tools/seo/keyword-density",
    icon: "Search",
    tags: ["seo", "keyword", "density", "analyzer"],
    keywords: ["keyword density", "keyword checker", "seo keywords"],
    isClientSide: true,
  },
  {
    id: "readability-score",
    name: "Readability Score Calculator",
    category: "seo",
    description: "Calculate readability scores (Flesch, SMOG, etc.)",
    route: "/tools/seo/readability-score",
    icon: "BookOpen",
    tags: ["seo", "readability", "score", "analyzer"],
    keywords: ["readability score", "readability checker", "text readability"],
    isClientSide: true,
  },
  {
    id: "heading-structure-analyzer",
    name: "Heading Structure Analyzer",
    category: "seo",
    description: "Analyze HTML heading structure (H1-H6)",
    route: "/tools/seo/heading-structure",
    icon: "Heading",
    tags: ["seo", "headings", "analyzer", "html"],
    keywords: ["heading structure", "h1 h2 h3", "heading analyzer"],
    isClientSide: true,
  },
  {
    id: "image-alt-text-generator",
    name: "Image Alt Text Generator",
    category: "seo",
    description: "Generate SEO-friendly alt text for images",
    route: "/tools/seo/alt-text-generator",
    icon: "Image",
    tags: ["seo", "alt text", "images", "accessibility"],
    keywords: ["alt text generator", "image alt text", "seo alt"],
    isClientSide: true,
  },
  {
    id: "canonical-url-generator",
    name: "Canonical URL Generator",
    category: "seo",
    description: "Generate canonical URL tags",
    route: "/tools/seo/canonical-url",
    icon: "Link",
    tags: ["seo", "canonical", "url", "meta"],
    keywords: ["canonical url", "canonical tag", "seo canonical"],
    isClientSide: true,
  },
  {
    id: "redirect-checker",
    name: "Redirect Checker",
    category: "seo",
    description: "Check HTTP redirects and status codes",
    route: "/tools/seo/redirect-checker",
    icon: "ArrowRight",
    tags: ["seo", "redirect", "http", "checker"],
    keywords: ["redirect checker", "http redirect", "check redirect"],
    isClientSide: false,
    isImplemented: true,
  },
  {
    id: "page-speed-analyzer",
    name: "Page Speed Analyzer",
    category: "seo",
    description: "Analyze page load speed and performance",
    route: "/tools/seo/page-speed",
    icon: "Gauge",
    tags: ["seo", "speed", "performance", "analyzer"],
    keywords: ["page speed", "speed test", "page performance"],
    isClientSide: false,
  },
  {
    id: "backlink-checker",
    name: "Backlink Checker",
    category: "seo",
    description: "Check backlinks for a URL",
    route: "/tools/seo/backlink-checker",
    icon: "Link",
    tags: ["seo", "backlinks", "checker", "links"],
    keywords: ["backlink checker", "check backlinks", "seo backlinks"],
    isClientSide: false,
  },
];

// Cloudinary Tools (12 tools)
const cloudinaryTools: Tool[] = [
  {
    id: "cloudinary-upload-transform",
    name: "Image Upload & Transform",
    category: "cloudinary",
    description: "Upload images to Cloudinary and apply transformations",
    route: "/tools/cloudinary/upload-transform",
    icon: "Upload",
    tags: ["cloudinary", "upload", "transform", "image"],
    keywords: ["cloudinary upload", "image transform", "cloudinary"],
    isClientSide: false,
    isImplemented: true,
  },
  {
    id: "cloudinary-optimization-wizard",
    name: "Image Optimization Wizard",
    category: "cloudinary",
    description: "Optimize images with Cloudinary's optimization features",
    route: "/tools/cloudinary/optimization-wizard",
    icon: "Sparkles",
    tags: ["cloudinary", "optimize", "image", "wizard"],
    keywords: ["cloudinary optimize", "image optimization", "optimize images"],
    isClientSide: false,
  },
  {
    id: "cloudinary-responsive-generator",
    name: "Responsive Image Generator",
    category: "cloudinary",
    description: "Generate responsive image URLs with srcset",
    route: "/tools/cloudinary/responsive-generator",
    icon: "Smartphone",
    tags: ["cloudinary", "responsive", "images", "srcset"],
    keywords: ["responsive images", "cloudinary responsive", "srcset"],
    isClientSide: true,
  },
  {
    id: "cloudinary-transformation-builder",
    name: "Image Transformation Builder",
    category: "cloudinary",
    description: "Build Cloudinary transformation URLs visually",
    route: "/tools/cloudinary/transformation-builder",
    icon: "Wrench",
    tags: ["cloudinary", "transform", "builder", "url"],
    keywords: ["cloudinary transform", "transformation builder", "image transform"],
    isClientSide: true,
  },
  {
    id: "cloudinary-video-upload",
    name: "Video Upload & Transform",
    category: "cloudinary",
    description: "Upload and transform videos with Cloudinary",
    route: "/tools/cloudinary/video-upload",
    icon: "Video",
    tags: ["cloudinary", "video", "upload", "transform"],
    keywords: ["cloudinary video", "video upload", "video transform"],
    isClientSide: false,
  },
  {
    id: "cloudinary-effects-gallery",
    name: "Image Effects Gallery",
    category: "cloudinary",
    description: "Apply Cloudinary effects to images",
    route: "/tools/cloudinary/effects-gallery",
    icon: "Palette",
    tags: ["cloudinary", "effects", "filters", "image"],
    keywords: ["cloudinary effects", "image effects", "cloudinary filters"],
    isClientSide: false,
  },
  {
    id: "cloudinary-overlay",
    name: "Image Overlay Tool",
    category: "cloudinary",
    description: "Add image overlays using Cloudinary",
    route: "/tools/cloudinary/overlay",
    icon: "Layers",
    tags: ["cloudinary", "overlay", "image", "combine"],
    keywords: ["cloudinary overlay", "image overlay", "overlay images"],
    isClientSide: false,
  },
  {
    id: "cloudinary-text-overlay",
    name: "Image Text Overlay",
    category: "cloudinary",
    description: "Add text overlays to images with Cloudinary",
    route: "/tools/cloudinary/text-overlay",
    icon: "Type",
    tags: ["cloudinary", "text", "overlay", "watermark"],
    keywords: ["cloudinary text", "text overlay", "image text"],
    isClientSide: false,
  },
  {
    id: "cloudinary-crop-resize",
    name: "Crop & Resize Wizard",
    category: "cloudinary",
    description: "Crop and resize images with Cloudinary transformations",
    route: "/tools/cloudinary/crop-resize",
    icon: "Crop",
    tags: ["cloudinary", "crop", "resize", "image"],
    keywords: ["cloudinary crop", "cloudinary resize", "crop resize"],
    isClientSide: false,
  },
  {
    id: "cloudinary-format-converter",
    name: "Image Format Converter",
    category: "cloudinary",
    description: "Convert image formats using Cloudinary",
    route: "/tools/cloudinary/format-converter",
    icon: "RefreshCw",
    tags: ["cloudinary", "format", "convert", "image"],
    keywords: ["cloudinary format", "convert format", "image converter"],
    isClientSide: false,
  },
  {
    id: "cloudinary-quality-optimizer",
    name: "Image Quality Optimizer",
    category: "cloudinary",
    description: "Optimize image quality with Cloudinary",
    route: "/tools/cloudinary/quality-optimizer",
    icon: "Star",
    tags: ["cloudinary", "quality", "optimize", "image"],
    keywords: ["cloudinary quality", "image quality", "optimize quality"],
    isClientSide: false,
  },
  {
    id: "cloudinary-url-generator",
    name: "Image Delivery URL Generator",
    category: "cloudinary",
    description: "Generate Cloudinary delivery URLs with transformations. Build optimized image URLs with resizing, cropping, quality adjustments, and effects. Perfect for developers using Cloudinary.",
    route: "/tools/cloudinary/url-generator",
    icon: "Link",
    tags: ["cloudinary", "url", "generator", "delivery"],
    keywords: ["cloudinary url", "image url generator", "cloudinary delivery"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["cloudinary-transformation-builder", "cloudinary-responsive-generator", "image-format-converter"],
  },
];

// Additional Tools (to reach 100+)
const colorTools: Tool[] = [
  {
    id: "color-picker",
    name: "Color Picker",
    category: "color",
    description: "Pick colors and get hex, RGB, HSL values",
    route: "/tools/color/picker",
    icon: "Droplet",
    tags: ["color", "picker", "hex", "rgb"],
    keywords: ["color picker", "color tool", "hex color"],
    isClientSide: true,
  },
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    category: "color",
    description: "Generate color palettes and schemes",
    route: "/tools/color/palette-generator",
    icon: "Palette",
    tags: ["color", "palette", "scheme", "generator"],
    keywords: ["color palette", "color scheme", "palette generator"],
    isClientSide: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    category: "color",
    description: "Convert between RGB, HEX, HSL color formats",
    route: "/tools/color/converter",
    icon: "RefreshCw",
    tags: ["color", "converter", "rgb", "hex", "hsl"],
    keywords: ["color converter", "rgb to hex", "hex to rgb"],
    isClientSide: true,
  },
  {
    id: "color-shades-generator",
    name: "Color Shades Generator",
    category: "color",
    description: "Generate color shades and tints",
    route: "/tools/color/shades-generator",
    icon: "Gradient",
    tags: ["color", "shades", "tints", "generator"],
    keywords: ["color shades", "shade generator", "color tints"],
    isClientSide: true,
  },
  {
    id: "color-contrast-checker",
    name: "Color Contrast Checker",
    category: "color",
    description: "Check color contrast for accessibility",
    route: "/tools/color/contrast-checker",
    icon: "Eye",
    tags: ["color", "contrast", "accessibility", "wcag"],
    keywords: ["color contrast", "contrast checker", "accessibility"],
    isClientSide: true,
  },
];

const encodingTools: Tool[] = [
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    category: "encoding",
    description: "Encode or decode URL-encoded strings",
    route: "/tools/encoding/url-encoder",
    icon: "Link",
    tags: ["url", "encode", "decode", "encoding"],
    keywords: ["url encoder", "url encode", "url decode"],
    isClientSide: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    category: "encoding",
    description: "Encode or decode Base64 strings",
    route: "/tools/encoding/base64-encoder",
    icon: "Lock",
    tags: ["base64", "encode", "decode", "encoding"],
    keywords: ["base64 encoder", "base64 encode", "base64 decode"],
    isClientSide: true,
  },
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder/Decoder",
    category: "encoding",
    description: "Encode or decode HTML entities",
    route: "/tools/encoding/html-entity",
    icon: "Code",
    tags: ["html", "entity", "encode", "decode"],
    keywords: ["html entity encoder", "html entities", "entity encoder"],
    isClientSide: true,
  },
  {
    id: "unicode-encoder",
    name: "Unicode Encoder/Decoder",
    category: "encoding",
    description: "Encode or decode Unicode strings",
    route: "/tools/encoding/unicode",
    icon: "Globe",
    tags: ["unicode", "encode", "decode", "encoding"],
    keywords: ["unicode encoder", "unicode encode", "unicode decode"],
    isClientSide: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    category: "encoding",
    description: "Decode JWT tokens and view payload",
    route: "/tools/encoding/jwt-decoder",
    icon: "Key",
    tags: ["jwt", "token", "decode", "json"],
    keywords: ["jwt decoder", "jwt token", "decode jwt"],
    isClientSide: true,
  },
];

const hashTools: Tool[] = [
  {
    id: "md5-generator",
    name: "MD5 Hash Generator",
    category: "hash",
    description: "Generate MD5 hash from text",
    route: "/tools/hash/md5",
    icon: "Fingerprint",
    tags: ["md5", "hash", "crypto"],
    keywords: ["md5 generator", "md5 hash", "md5"],
    isClientSide: true,
  },
  {
    id: "sha1-generator",
    name: "SHA1 Hash Generator",
    category: "hash",
    description: "Generate SHA1 hash from text",
    route: "/tools/hash/sha1",
    icon: "Fingerprint",
    tags: ["sha1", "hash", "crypto"],
    keywords: ["sha1 generator", "sha1 hash", "sha1"],
    isClientSide: true,
  },
  {
    id: "sha256-generator",
    name: "SHA256 Hash Generator",
    category: "hash",
    description: "Generate SHA256 hash from text",
    route: "/tools/hash/sha256",
    icon: "Fingerprint",
    tags: ["sha256", "hash", "crypto"],
    keywords: ["sha256 generator", "sha256 hash", "sha256"],
    isClientSide: true,
  },
  {
    id: "sha512-generator",
    name: "SHA512 Hash Generator",
    category: "hash",
    description: "Generate SHA512 hash from text",
    route: "/tools/hash/sha512",
    icon: "Fingerprint",
    tags: ["sha512", "hash", "crypto"],
    keywords: ["sha512 generator", "sha512 hash", "sha512"],
    isClientSide: true,
  },
  {
    id: "bcrypt-generator",
    name: "BCrypt Hash Generator",
    category: "hash",
    description: "Generate BCrypt hashes from text securely. BCrypt is a strong password hashing algorithm used for storing passwords. Perfect for developers implementing authentication systems.",
    route: "/tools/hash/bcrypt",
    icon: "Fingerprint",
    tags: ["bcrypt", "hash", "crypto", "password"],
    keywords: ["bcrypt generator", "bcrypt hash", "bcrypt"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["md5-generator", "sha256-generator", "sha512-generator"],
  },
];

const qrCodeTools: Tool[] = [
  {
    id: "qr-code-generator-standalone",
    name: "QR Code Generator",
    category: "qr-code",
    description: "Generate QR codes from text or URLs instantly. Create scannable QR codes for websites, contact information, WiFi passwords, and more. Customize size and error correction level for optimal scanning.",
    route: "/tools/qr-code/generator",
    icon: "QrCode",
    tags: ["qr code", "generator", "barcode"],
    keywords: ["qr code generator", "generate qr", "qr code"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["qr-code-reader-standalone", "qr-code-customizer"],
  },
  {
    id: "qr-code-reader-standalone",
    name: "QR Code Reader",
    category: "qr-code",
    description: "Read and decode QR codes from images",
    route: "/tools/qr-code/reader",
    icon: "Scan",
    tags: ["qr code", "reader", "decode"],
    keywords: ["qr code reader", "read qr", "qr decoder"],
    isClientSide: true,
  },
  {
    id: "qr-code-customizer",
    name: "QR Code Customizer",
    category: "qr-code",
    description: "Generate customized QR codes with colors and logos",
    route: "/tools/qr-code/customizer",
    icon: "Palette",
    tags: ["qr code", "customize", "colors", "logo"],
    keywords: ["qr code customizer", "custom qr code", "colored qr"],
    isClientSide: true,
  },
];

const dateTimeTools: Tool[] = [
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    category: "date-time",
    description: "Convert between Unix timestamps and dates instantly. Perfect for developers working with APIs, log files, databases, and scheduling systems. Supports both timestamp-to-date and date-to-timestamp conversions.",
    route: "/tools/date-time/timestamp-converter",
    icon: "Clock",
    tags: ["timestamp", "date", "convert", "unix"],
    keywords: ["timestamp converter", "unix timestamp", "date converter"],
    isClientSide: true,
    isImplemented: true,
    relatedToolIds: ["timezone-converter", "date-calculator", "age-calculator"],
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    category: "date-time",
    description: "Calculate date differences and add/subtract time",
    route: "/tools/date-time/date-calculator",
    icon: "Calculator",
    tags: ["date", "calculator", "difference", "time"],
    keywords: ["date calculator", "date difference", "date math"],
    isClientSide: true,
  },
  {
    id: "timezone-converter",
    name: "Time Zone Converter",
    category: "date-time",
    description: "Convert times between different time zones",
    route: "/tools/date-time/timezone-converter",
    icon: "Globe",
    tags: ["timezone", "convert", "time", "zone"],
    keywords: ["timezone converter", "time zone", "convert timezone"],
    isClientSide: true,
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    category: "date-time",
    description: "Calculate age from birth date",
    route: "/tools/date-time/age-calculator",
    icon: "BirthdayCake",
    tags: ["age", "calculator", "birthday", "date"],
    keywords: ["age calculator", "calculate age", "birthday calculator"],
    isClientSide: true,
  },
  {
    id: "countdown-timer",
    name: "Countdown Timer",
    category: "date-time",
    description: "Create countdown timers for events",
    route: "/tools/date-time/countdown-timer",
    icon: "Timer",
    tags: ["countdown", "timer", "event", "time"],
    keywords: ["countdown timer", "timer", "countdown"],
    isClientSide: true,
  },
];

const unitConverterTools: Tool[] = [
  {
    id: "length-converter",
    name: "Length Converter",
    category: "unit-converter",
    description: "Convert between length units (meters, feet, inches, etc.)",
    route: "/tools/unit-converter/length",
    icon: "Ruler",
    tags: ["length", "convert", "units", "distance"],
    keywords: ["length converter", "distance converter", "unit converter"],
    isClientSide: true,
  },
  {
    id: "weight-converter",
    name: "Weight Converter",
    category: "unit-converter",
    description: "Convert between weight units (kg, lbs, oz, etc.)",
    route: "/tools/unit-converter/weight",
    icon: "Scale",
    tags: ["weight", "convert", "units", "mass"],
    keywords: ["weight converter", "mass converter", "unit converter"],
    isClientSide: true,
  },
  {
    id: "temperature-converter",
    name: "Temperature Converter",
    category: "unit-converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    route: "/tools/unit-converter/temperature",
    icon: "Thermometer",
    tags: ["temperature", "convert", "celsius", "fahrenheit"],
    keywords: ["temperature converter", "celsius fahrenheit", "temp converter"],
    isClientSide: true,
  },
  {
    id: "volume-converter",
    name: "Volume Converter",
    category: "unit-converter",
    description: "Convert between volume units (liters, gallons, etc.)",
    route: "/tools/unit-converter/volume",
    icon: "Droplet",
    tags: ["volume", "convert", "units", "liquid"],
    keywords: ["volume converter", "liquid converter", "unit converter"],
    isClientSide: true,
  },
  {
    id: "speed-converter",
    name: "Speed Converter",
    category: "unit-converter",
    description: "Convert between speed units (km/h, mph, m/s, etc.)",
    route: "/tools/unit-converter/speed",
    icon: "Gauge",
    tags: ["speed", "convert", "units", "velocity"],
    keywords: ["speed converter", "velocity converter", "unit converter"],
    isClientSide: true,
  },
];

// Combine all tools
export const allTools: Tool[] = [
  ...jsonTools,
  ...textTools,
  ...imageTools,
  ...pdfTools,
  ...htmlTools,
  ...seoTools,
  ...cloudinaryTools,
  ...colorTools,
  ...encodingTools,
  ...hashTools,
  ...qrCodeTools,
  ...dateTimeTools,
  ...unitConverterTools,
];

// Category information
export const toolCategories: ToolCategoryInfo[] = [
  {
    id: "json",
    name: "JSON Tools",
    description: "Format, validate, convert, and manipulate JSON data",
    icon: "FileJson",
    color: "text-yellow-600",
    toolCount: jsonTools.length,
  },
  {
    id: "text",
    name: "Text Tools",
    description: "Transform, analyze, and manipulate text content",
    icon: "Type",
    color: "text-blue-600",
    toolCount: textTools.length,
  },
  {
    id: "image",
    name: "Image Tools",
    description: "Resize, compress, convert, and edit images",
    icon: "Image",
    color: "text-purple-600",
    toolCount: imageTools.length,
  },
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Convert, merge, split, and manipulate PDF files",
    icon: "FileText",
    color: "text-red-600",
    toolCount: pdfTools.length,
  },
  {
    id: "html",
    name: "HTML Tools",
    description: "Format, validate, convert, and analyze HTML code",
    icon: "Code",
    color: "text-orange-600",
    toolCount: htmlTools.length,
  },
  {
    id: "seo",
    name: "SEO Tools",
    description: "Generate meta tags, sitemaps, and optimize for search engines",
    icon: "Search",
    color: "text-green-600",
    toolCount: seoTools.length,
  },
  {
    id: "cloudinary",
    name: "Cloudinary Tools",
    description: "Upload, transform, and optimize images with Cloudinary",
    icon: "Cloud",
    color: "text-cyan-600",
    toolCount: cloudinaryTools.length,
  },
  {
    id: "color",
    name: "Color Tools",
    description: "Pick, convert, and generate color palettes",
    icon: "Palette",
    color: "text-pink-600",
    toolCount: colorTools.length,
  },
  {
    id: "encoding",
    name: "Encoding Tools",
    description: "Encode and decode various formats",
    icon: "Lock",
    color: "text-indigo-600",
    toolCount: encodingTools.length,
  },
  {
    id: "hash",
    name: "Hash Tools",
    description: "Generate cryptographic hashes",
    icon: "Fingerprint",
    color: "text-gray-600",
    toolCount: hashTools.length,
  },
  {
    id: "qr-code",
    name: "QR Code Tools",
    description: "Generate and read QR codes",
    icon: "QrCode",
    color: "text-teal-600",
    toolCount: qrCodeTools.length,
  },
  {
    id: "date-time",
    name: "Date & Time Tools",
    description: "Convert timestamps, calculate dates, and manage time zones",
    icon: "Clock",
    color: "text-amber-600",
    toolCount: dateTimeTools.length,
  },
  {
    id: "unit-converter",
    name: "Unit Converters",
    description: "Convert between different units of measurement",
    icon: "Ruler",
    color: "text-slate-600",
    toolCount: unitConverterTools.length,
  },
];

// Helper functions
export function getToolsByCategory(category: string): Tool[] {
  return allTools.filter((tool) => tool.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return allTools.find((tool) => tool.id === id);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return allTools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)) ||
      tool.keywords.some((keyword) => keyword.toLowerCase().includes(lowerQuery))
  );
}

export function getCategoryInfo(category: string) {
  return toolCategories.find((cat) => cat.id === category);
}

// Total tool count
export const totalToolCount = allTools.length;

